### ISSUE TITLE
Neovim/Windows: no output from maker jobs

### ISSUE THREAD

**Issue by HankelBao** [neomake/neomake#1955]
### Expected behavior

Showing up proper content in the location list window.

### Steps to reproduce

I'm using Neovim on Windows.
After running :Neomake in a .py file it pops up a cmd window and the window closed right after.
It shows nothing in the location list window.
Everything looks fine in the log file.

### Output from (verbose) NeomakeInfo

16:39:07 [D      ] [24.-:1:1] Exe (frosted) of auto-configured maker frosted is not executable, skipping.
16:39:07 [D +0.02] [24.-:1:1] Running makers: python (auto), pyflakes (auto), pycodestyle (auto), pydocstyle (auto), pylint (auto).
16:39:07 [D      ] [24.23:1:1] Setting neomake_automake_tick.
16:39:07 [V      ] [24.23:1:1] Starting async job [string]: cmd.exe /c python "C:\Users\hankelbao\.vim\plugged\neomake\autoload\neomake\makers\ft\python\compile.py" "C:\Users\hankelbao\Workspace\test\test.py".
16:39:07 [D      ] [24.23:1:1] cwd: C:\Users\hankelbao.
16:39:07 [D +0.25] [24.23:1:1] exit: python: 1.
16:39:07 [D +0.01] [24.23:1:1] python: completed with exit code 1.
16:39:07 [V      ] [24.-:-:1] Aborting next makers: pyflakes, pycodestyle, pydocstyle, pylint.
16:39:07 [D      ] [24.23:1:1] Cleaning jobinfo.
16:39:07 [D      ] [24.-:1:1] File-level errors cleaned.
16:39:07 [D      ] [24.-:-:1] Cleaning location list.
16:39:07 [D      ] [24.-:1:1] Cleaning make info.
16:39:36 [D +28.6] [25.-:1:1] Running makers: pep8.
16:39:36 [D      ] [25.24:1:1] Setting neomake_automake_tick.
16:39:36 [V      ] [25.24:1:1] Starting async job [string]: cmd.exe /c pycodestyle "C:\Users\hankelbao\Workspace\test\test.py".
16:39:36 [D      ] [25.24:1:1] cwd: C:\Users\hankelbao.
16:39:36 [D +0.33] [25.24:1:1] exit: pep8: 1.
16:39:36 [D +0.01] [25.24:1:1] pep8: completed with exit code 1.
16:39:36 [D      ] [25.24:1:1] Cleaning jobinfo.
16:39:36 [D      ] [25.-:1:1] File-level errors cleaned.
16:39:36 [D      ] [25.-:-:1] Cleaning location list.
16:39:36 [D      ] [25.-:1:1] Cleaning make info.

**Comment by blueyed** [comment]
There is no log information about any output.

Does running `cmd.exe /c pycodestyle "C:\Users\hankelbao\Workspace\test\test.py"` manually work / produce output?

Which Neovim version are you using?
Can you try it with Vim?

**Comment by HankelBao** [comment]
Yes, it produces correct output.
I'm using Neovim 0.2.2.
I've just tried with GVim and it works fine.

**Comment by blueyed** [comment]
> it pops up a cmd window and the window closed right after

Does this also happen with GVim?
I think this should be avoided.

There are fixes regarding Windows in Neovim master (to become 0.3.0), maybe that helps here?!
You could try it using the pre-release via https://github.com/neovim/neovim/wiki/Installing-Neovim#windows.

Apart from that I've tried fixing args handling in https://github.com/neomake/neomake/pull/1896, but got blocked by setting up AppVeyor to really test it (https://github.com/neomake/neomake/pull/1575).

**Comment by HankelBao** [comment]
No, it doesn't happen in GVim.
I tried and Neovim 0.3.0-dev solved my problem.
Thank you!

**Comment by blueyed** [comment]
Cool!

I guess it's related to https://github.com/neomake/neomake/blob/e106e2d552e6d72f1ffbda7b1821e743fd682825/autoload/neomake.vim#L413-L416 then.
1. can you try commenting those lines?  Does it work in Neovim 0.2.2 and 0.3 then?
2. can you try changing those lines to just `let opts.pty = 1`, and then try it with both Neovim 0.2.2 and 0.3 again?

**Comment by HankelBao** [comment]
If I comment those lines,
    In both version, there are contents in the location list and they both work correctly.(seems problem solves)
If I change those lines to let opts.pty = 1,
    In Neovim 0.2.2, there are lines of information in the location list but they are incomplete(can only display several words per line) and there are some strange characters like ^[[0m^[[0K
    In Neovim 0.3.0, it works correctly.

**Comment by blueyed** [comment]
Thanks for the detailed information.
Should be fixed now.

**Comment by DahliaSR** [comment]
I can confirm that this DOES NOT fix the issue.  
The problem still is the same.

https://github.com/neomake/neomake/blob/8e72d2e6c9a68ee0487eec703848e6bd7acdc41e/autoload/neomake.vim#L413-L418

Changing line 418 to: 

```vim
        let opts.detach = 0
```
fixes the issue for nvim 0.2.2 and also works with nvim 0.3.0

**Comment by blueyed** [comment]
@DahliaSR 
Thanks for the report, should be fixed now really - the logic was wrong.

**Comment by DahliaSR** [comment]
@blueyed 
Confirmed - Now it works as expected for me.

Thx.
