### ISSUE TITLE
Python: pep8 was renamed to pycodestyle

### ISSUE THREAD

**Issue by languitar** [neomake/neomake#487]
https://github.com/PyCQA/pycodestyle/issues/466

The changed name should somehow be reflected in the python makers while allowing to use old versions still called `pep8`.

**Comment by blueyed** [comment]
Same applies to `pep257` / `pydocstyle`.
I've started working on the pep257 one already.

**Comment by blueyed** [comment]
Fixed by now.

**Comment by zoresvit** [comment]
Still doesn't seem to work for me. When I have `pycodestyle` installed, Neomake ignores it during linting, and if I explicitly set:
```
let g:neomake_python_enabled_makers = ['pycodestyle']
```

I get the following error:
```
Neomake: [?] Maker not found (for filetypes ['python']): pycodestyle
```

With pep8 everything works as expected.

**Comment by blueyed** [comment]
Oh, I've confused it with pydocstyle probably.

**Comment by blueyed** [comment]
@zoresvit 
Do you feel like creating a PR for it?

**Comment by zoresvit** [comment]
@blueyed 
Sure! Thanks for confirming it wasn't just a configuration problem.

I'm not good with VimL, but thanks to your clean code I could adopt the solution for PEP257 to PEP8/pycodestyle as well (mostly by copy-paste). So please feel free to let me know if I did anything stupid in #1113 :)

PS: A bit offtopic, but I've also noticed that since commit [eeb023](https://github.com/neomake/neomake/commit/eeb023e3b54d3251e8c594e0697ef048201f8d6b) Python makes would not show up by default, so I have to explicitly set
```
let g:neomake_python_enabled_makers = ['pylint', 'pycodestyle', 'pydocstyle'] 
```
Will look more into it, maybe this should be a separate issue.

**Comment by blueyed** [comment]
@zoresvit 
Thanks!
Yes, please create a new issue for it.
It might be something trivial, but the more information the easier for me.

**Comment by blueyed** [comment]
@zoresvit 
FWIW, I could not reproduce your other issue.  So check your other settings if any, and if it is still a problem then please file a new issue, with the logfile.

**Comment by zoresvit** [comment]
@blueyed 
You are right, that was the problem! I didn't have `frosted` package, so every maker after it failed to run. With #1116 everything works now.

Thanks!

**Comment by blueyed** [comment]
Great!
