### ISSUE TITLE
Rust/Cargo: :Neomake! cargo messes up cargo...

### ISSUE THREAD

**Issue by Ploppz** [neomake/neomake#847]
Same setup as in [previous issue I posted](https://github.com/neomake/neomake/issues/846). I just need to say that after running `:Neomake! cargo`, whenever I run `cargo build` or `cargo run` again, it says `Blocking waiting for file lock on build directory` for a while before continuing. This message was a problem to me earlier, making strange behaviour.

I tried to grep `ps aux` for cargo, rust, neomake, make, etc, but it doesn't seem like `:Neomake` keeps running or something so that's not the problem.

**Comment by fuine** [comment]
`cargo` has a blocking feature - you can't compile the same project more than once at the same time. Because `cargo` checker uses `cargo` binary to compile the project and read possible errors/warnings any use of the maker will effectively block the 'normal' compilation of the project outside of neovim. This is not a bug, nor a feature, but rather a significant inconvenience that we are facing now. 

Please check out #843 to see the upcoming changes, which will hopefully significantly reduce the time during which `cargo` maker blocks the compilation of the project.

**Comment by blueyed** [comment]
So in this case using `timeout` or (manually) stopping the job might help?!
What is the process that locks it?

**Comment by blueyed** [comment]
Maybe even stop it from post processing when there is no output for e.g. 2s?

**Comment by fuine** [comment]
The process is compilation itself. Adding timeout would probably help, but then it'd possible that maker wouldn't get any warnings, as they come up later in the process of compilation. Also you need to build the project first, in order to build the tests, so stopping too early could result in not catching errors in tests. This is not an easily fixed problem, i hope that `cargo-check` will aid the times and so we won't have to resort to any timeout.

**Comment by Ploppz** [comment]
Until it is resolved with `cargo-check`: it would already be much better if `cargo build` doesn't have to recompile the project right after Neomake has run `cargo build` (if that's what it runs for syntax checking etc). That is: Neomake should actually compile the project. Right now it is as if it spends as much time as would be required to compile the project, but doing no useful work.

Can this be done?

**Comment by fuine** [comment]
This issue should be resolved by #1195. @Ploppz can you get the new version and confirm that is the case?

**Comment by blueyed** [comment]
Closing for now already, please report back / re-open accordingly.

**Comment by jupart** [comment]
For me and my use case, this is still an issue. If I put Neovim in the background (with `Ctrl-z`) shortly after a `:w`, a lock is created. Then I can't `cargo build` or `cargo check` until I bring Neovim back into the `fg` and let it finish compiling.

**Comment by blueyed** [comment]
@jupart 
Would using `cargo check --tests` help with that?
See https://github.com/neomake/neomake/issues/843#issuecomment-301596346 (and the one above).
Please try changing this setting.

**Comment by blueyed** [comment]
@jupart 
`['check']` is the default.. please try `['check', '--test']` or whatever might not take a lock.  Is there something?
According to https://github.com/rust-lang/cargo/commit/235712f5998d223895282e5e52b228808ac02f13 it should not compile at least ("Don't implicitly compile binaries when using just `--test` filters.").

**Comment by jupart** [comment]
Indeed, that setting doesn't create a lock. Sorry for the noise!

--

Justin Partain
